ALTER TABLE properties ADD COLUMN bedrooms INTEGER NOT NULL DEFAULT 0;
ALTER TABLE properties ADD COLUMN bathrooms INTEGER NOT NULL DEFAULT 0;
ALTER TABLE properties ADD COLUMN front_yard TEXT NOT NULL DEFAULT '';
ALTER TABLE properties ADD COLUMN back_yard TEXT NOT NULL DEFAULT '';
ALTER TABLE properties ADD COLUMN car_yard TEXT NOT NULL DEFAULT '';
ALTER TABLE properties ADD COLUMN terrace TEXT NOT NULL DEFAULT '';
ALTER TABLE properties ADD COLUMN function_text TEXT NOT NULL DEFAULT '';
